twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        uploads_cv: '%uploads_cv%'
        uploads_image_profile: '%uploads_image_profile%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        
when@test:
    twig:
        strict_variables: true
