vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        cv_file:
            uri_prefix: '%uploads_cv%'
            upload_destination: '%kernel.project_dir%/public%uploads_cv%'
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image_profile:
            uri_prefix: '%uploads_image_profile%'
            upload_destination: '%kernel.project_dir%/public%uploads_image_profile%'
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
